extends:
  - ../../.eslintrc.yml
rules:
  '@typescript-eslint/interface-name-prefix':
    - off
  '@typescript-eslint/no-non-null-assertion':
    - off
  '@typescript-eslint/no-object-literal-type-assertion':
    - off
  '@typescript-eslint/no-parameter-properties':
    - off